package vista;

import Lista.ListaP;
import controlador.ControladorInterfaz;
import controlador.LeerGuardar;
import controlador.OperGramatica;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public final class visual extends javax.swing.JFrame {
    
    LeerGuardar inOut = new LeerGuardar();
    ControladorInterfaz control = new ControladorInterfaz();
    String gramaSimpli="";
    boolean gramValid;
    ListaP lista= new ListaP();
    ListaP listaSimpli= new ListaP();
    OperGramatica op = new OperGramatica();
    ArrayList<String> listaVi=new ArrayList<String>();
    ArrayList<String> listaMu=new ArrayList<String>();
    ArrayList<String> listaAl=new ArrayList<String>();
    ArrayList<String> listaIna=new ArrayList<String>();
    String [][] autoMatriz;
    public visual() {
        initComponents();
        control.iniciarBotones(validar, guardarA, autDeterm, simplificar);
        control.iniciarText(jTextField1, textAreaG, textAreaVMI);
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        textAreaG = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        textAreaVMI = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        validar = new javax.swing.JButton();
        insertar = new javax.swing.JButton();
        actualizar = new javax.swing.JButton();
        guardarG = new javax.swing.JButton();
        guardarA = new javax.swing.JButton();
        autDeterm = new javax.swing.JButton();
        simplificar = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        textAreaG.setColumns(20);
        textAreaG.setRows(5);
        jScrollPane2.setViewportView(textAreaG);

        textAreaVMI.setColumns(20);
        textAreaVMI.setRows(5);
        jScrollPane3.setViewportView(textAreaVMI);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        validar.setText("Validar");
        validar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validarActionPerformed(evt);
            }
        });

        insertar.setText("Insertar");
        insertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertarActionPerformed(evt);
            }
        });

        actualizar.setText("Actualizar");

        guardarG.setText("Guardar Gram.");
        guardarG.setToolTipText("");
        guardarG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarGActionPerformed(evt);
            }
        });

        guardarA.setText("Guardar Aut.");

        autDeterm.setText("Aut. Determinístico");
        autDeterm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autDetermActionPerformed(evt);
            }
        });

        simplificar.setText("Simplificar Aut.");
        simplificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simplificarActionPerformed(evt);
            }
        });

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tabla);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(insertar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(guardarG, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(guardarA, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(validar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(simplificar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(autDeterm, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 257, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(validar)
                    .addComponent(autDeterm))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(insertar)
                    .addComponent(actualizar)
                    .addComponent(guardarG)
                    .addComponent(guardarA)
                    .addComponent(simplificar))
                .addGap(18, 18, 18)
                .addComponent(salir)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void validarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validarActionPerformed

    }//GEN-LAST:event_validarActionPerformed

    private void autDetermActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autDetermActionPerformed
        
    }//GEN-LAST:event_autDetermActionPerformed

    private void guardarGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarGActionPerformed
        try {
            inOut.guardarTxt(jTextArea1);
        } catch (IOException ex) {
            Logger.getLogger(visual.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_guardarGActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
       dispose();
    }//GEN-LAST:event_salirActionPerformed

    private void insertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertarActionPerformed
        try {
            String gramatica = inOut.leerTxt();
            gramValid = inOut.validarGram(gramatica);
            if(gramValid){
                jTextArea1.setText(gramatica);
                lista=OperGramatica.graToLista(gramatica);
                //OperGramatica.recorrer(lista.getPrimer().getLigaD());
                if(!lista.esVacia(lista)){
                listaSimpli=lista;
                OperGramatica.listaTermi(lista);
                listaVi=OperGramatica.listaNomu(lista);
                listaAl=OperGramatica.listaAlcan(lista);
                listaMu=OperGramatica.listaMuertos(lista);
                listaIna=OperGramatica.listaInalcanzables(lista);
                String datos="";
                if(!listaVi.isEmpty()){
                datos="Estos son los no terminales Vivos\n";
                for(int i=0;i<listaVi.size();i++){
                    datos=datos+"<"+listaVi.get(i)+">"+"\n";                
                }
                
                }
                if(!listaMu.isEmpty()){
                datos=datos+"Estos los no terminales muertos\n";
                for(int i=0;i<listaMu.size();i++){
                    datos=datos+"<"+listaMu.get(i)+">"+"\n";                
                }
                lista.desconectar(listaSimpli, listaMu);
                }
                
                if(!listaIna.isEmpty()){
                datos=datos+"Estos los no terminales Inalcanzables\n";
                for(int i=0;i<listaIna.size();i++){
                    datos=datos+"<"+listaIna.get(i)+">"+"\n";                
                }
                lista.desconectar(listaSimpli, listaIna);
                }
                textAreaVMI.setText(datos);
                
                if((listaMu.isEmpty())&&(listaIna.isEmpty()))
                    JOptionPane.showMessageDialog(null,"No es posible simplificar la gramatica");
                else{
                    gramaSimpli=OperGramatica.toGrama(listaSimpli);
                    textAreaG.setText(gramaSimpli);
                }
                    
        
        }
        else
            JOptionPane.showMessageDialog(null,"No se ha ingresado ninguna gramatica");
                boolean v = op.formaEspecial(listaSimpli);                //¡IMPORTANTE! AQUÍ VA LA GRAMÁTICA SIMPLIFICADA......Mover esta funcion al boton generar automata!!!!
                ArrayList<String> listaEntradas=OperGramatica.listaEntrad(lista);
                ArrayList<String> listaEntrad=OperGramatica.listaEsta(lista);
                autoMatriz=OperGramatica.autoMatriz(lista);
                 //System.out.println(listaEntrad.size());
               
                
                
            } else{
                JOptionPane.showMessageDialog(null, "La gramática ingresada no es válida");
            }
            
        } catch (IOException ex) {
            Logger.getLogger(visual.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_insertarActionPerformed

    private void simplificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simplificarActionPerformed
        
        
    }//GEN-LAST:event_simplificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new visual().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizar;
    private javax.swing.JButton autDeterm;
    private javax.swing.JButton guardarA;
    private javax.swing.JButton guardarG;
    private javax.swing.JButton insertar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton salir;
    private javax.swing.JButton simplificar;
    private javax.swing.JTable tabla;
    private javax.swing.JTextArea textAreaG;
    private javax.swing.JTextArea textAreaVMI;
    private javax.swing.JButton validar;
    // End of variables declaration//GEN-END:variables
}
